version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - NYPL_API_KEY=mqwifkgv1yhkbbon  # This is the API key
    volumes:
      - ./frontend/templates:/app/templates
      - ./frontend/static:/app/static
