version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NYPL_API_KEY=mqwifkgv1yhkbbon  # <-- Your API key here
    volumes:
      - ./frontend/templates:/app/templates
      - ./frontend/static:/app/static